---
- name: Remove Nginx, Gunicorn, and Flask setup on Ubuntu
  hosts: all
  become: true

  vars:
    user: "ubuntu"
    project_name: "dj-project"
    project_dir: "/home/{{ user }}/{{ project_name }}"
    domain_name: "dj.insidenet.net"
    gunicorn_service_file: "/etc/systemd/system/gunicorn.service"
    nginx_conf_file: "/etc/nginx/sites-available/{{ project_name }}"
    nginx_enabled_file: "/etc/nginx/sites-enabled/{{ project_name }}"
    packages:
      - nginx
      - python3-venv
      - python3-pip
      - certbot
      - python3-certbot-nginx
    files_to_remove:
      - "{{ gunicorn_service_file }}"
      - "{{ nginx_conf_file }}"
      - "{{ nginx_enabled_file }}"
      - "{{ project_dir }}"

  tasks:
    - name: Stop and disable Gunicorn service
      systemd:
        name: gunicorn
        state: stopped
        enabled: no
      failed_when: false
      ignore_errors: true

    - name: Remove files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ files_to_remove }}"

    - name: Stop Nginx service
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes
      failed_when: false

    - name: Remove Nginx packages
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - nginx
        - nginx-core
        - nginx-common
      ignore_errors: yes

    - name: Perform autoremove
      apt:
        autoremove: yes
        purge: yes

    - name: Clean up apt cache
      apt:
        autoclean: yes

    - name: Check if certbot is installed
      stat:
        path: /usr/bin/certbot
      register: certbot_installed

    - name: Remove Let's Encrypt SSL certificate
      command: certbot delete --cert-name {{ domain_name }}
      when: certbot_installed.stat.exists
      ignore_errors: yes
      failed_when: false

    - name: Uninstall packages installed by apt
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop: "{{ packages }}"
      ignore_errors: yes

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes
        purge: yes

    - name: Clean up apt cache
      apt:
        autoclean: yes

    - name: Remove any remaining configuration files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/log/nginx
        - /var/log/gunicorn
        - /etc/letsencrypt
        - /home/ubuntu/dj-project
