---
- name: Remove Nginx, Gunicorn, and Flask setup on Ubuntu
  hosts: vpn_server
  become: true

  vars:
    user: "ubuntu"
    project_name: "dj-project"
    project_dir: "/home/{{ user }}/{{ project_name }}"
    domain_name: "dj.insidenet.net"
    gunicorn_service_file: "/etc/systemd/system/gunicorn.service"
    nginx_conf_file: "/etc/nginx/sites-available/{{ project_name }}"
    nginx_enabled_file: "/etc/nginx/sites-enabled/{{ project_name }}"
    packages:
      - nginx
      - python3-venv
      - python3-pip
      - certbot
      - python3-certbot-nginx
    files_to_remove:
      - "{{ gunicorn_service_file }}"
      - "{{ nginx_conf_file }}"
      - "{{ nginx_enabled_file }}"
      - "{{ project_dir }}"

  tasks:
    - name: Stop and disable Gunicorn service
      systemd:
        name: gunicorn
        state: stopped
        enabled: no
      failed_when: false
      ignore_errors: true

    - name: Remove files and directories
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ files_to_remove }}"

    - name: Check if Nginx is installed
      stat:
        path: /usr/sbin/nginx
      register: nginx_installed

    - name: Unmask Nginx service if installed and masked
      command: systemctl unmask nginx
      when: nginx_installed.stat.exists

    - name: Restart Nginx to apply changes if installed
      systemd:
        name: nginx
        state: restarted
      when: nginx_installed.stat.exists
      failed_when: false
      ignore_errors: true

    - name: Check if certbot is installed
      stat:
        path: /usr/bin/certbot
      register: certbot_installed

    - name: Remove Let's Encrypt SSL certificate
      command: certbot delete --cert-name {{ domain_name }}
      when: certbot_installed.stat.exists
      ignore_errors: yes

    - name: Uninstall packages installed by apt
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop: "{{ packages }}"

    - name: Autoremove unnecessary packages
      apt:
        name: "*"
        state: latest
        autoremove: yes
        purge: yes

    - name: Clean up apt cache
      apt:
        update_cache: yes
        autoclean: yes
